package br.com.itengine.score.entity;//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import javax.persistence.*;

@Entity
public class Action implements Serializable {

    @OneToOne(targetEntity = ActionType.class)
    private ActionType actionType;

    @Id
    @GeneratedValue(generator = "id", strategy = GenerationType.SEQUENCE)
    @SequenceGenerator(name = "id")
    private Long id;

    private String minute;

    @OneToOne(targetEntity = Player.class)
    private Player player;

    public Action() {

    }

    public ActionType getActionType() {
        return this.actionType;
    }

    public void setActionType(ActionType actionType) {
        this.actionType = actionType;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMinute() {
        return this.minute;
    }

    public void setMinute(String minute) {
        this.minute = minute;
    }

    public Player getPlayer() {
        return this.player;
    }

    public void setPlayer(Player player) {
        this.player = player;
    }
}
