package br.com.itengine.score.entity;//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.*;

@Entity
public class Match implements Serializable {

    @ManyToOne(targetEntity = User.class)
    private User delegate;

    @ManyToOne(optional = false, targetEntity = Team.class)
    private Team teamVisitor;

    private boolean isPlayed;

    private Date dateOfMatch;

    private boolean isPostponed;

    @ManyToOne(optional = false, targetEntity = Team.class)
    private Team teamHome;

    @Id
    @GeneratedValue(generator = "id", strategy = GenerationType.SEQUENCE)
    @SequenceGenerator(name = "id")
    private Integer id;

    @OneToMany(cascade = {CascadeType.ALL}, targetEntity = Action.class)
    private List<Action> actions;

    public Match() {

    }

    public User getDelegate() {
        return this.delegate;
    }

    public void setDelegate(User delegate) {
        this.delegate = delegate;
    }

    public Team getTeamVisitor() {
        return this.teamVisitor;
    }

    public void setTeamVisitor(Team teamVisitor) {
        this.teamVisitor = teamVisitor;
    }

    public boolean isIsPlayed() {
        return this.isPlayed;
    }

    public void setIsPlayed(boolean isPlayed) {
        this.isPlayed = isPlayed;
    }

    public Date getDateOfMatch() {
        return this.dateOfMatch;
    }

    public void setDateOfMatch(Date dateOfMatch) {
        this.dateOfMatch = dateOfMatch;
    }

    public boolean isIsPostponed() {
        return this.isPostponed;
    }

    public void setIsPostponed(boolean isPostponed) {
        this.isPostponed = isPostponed;
    }

    public Team getTeamHome() {
        return this.teamHome;
    }

    public void setTeamHome(Team teamHome) {
        this.teamHome = teamHome;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public List<Action> getActions() {
        return this.actions;
    }

    public void setActions(List<Action> actions) {
        this.actions = actions;
    }
}
