package br.com.itengine.score.entity;//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

@Entity
public class Match implements Serializable {

    @ManyToOne(targetEntity = User.class)
    private User delegate;

    @OneToOne(targetEntity = Team.class)
    private Team teamVisitor;

    private String isPlayed;

    private String dateOfMatch;

    private String isPostponed;

    @OneToOne(targetEntity = Team.class)
    private Team teamHome;

    @Id
    @GeneratedValue(generator = "id", strategy = GenerationType.SEQUENCE)
    @SequenceGenerator(name = "id")
    private Long id;

    @OneToMany(targetEntity = Action.class)
    private List<Action> actions;

    public Match() {

    }

    public User getDelegate() {
        return this.delegate;
    }

    public void setDelegate(User delegate) {
        this.delegate = delegate;
    }

    public Team getTeamVisitor() {
        return this.teamVisitor;
    }

    public void setTeamVisitor(Team teamVisitor) {
        this.teamVisitor = teamVisitor;
    }

    public String getIsPlayed() {
        return this.isPlayed;
    }

    public void setIsPlayed(String isPlayed) {
        this.isPlayed = isPlayed;
    }

    public String getDateOfMatch() {
        return this.dateOfMatch;
    }

    public void setDateOfMatch(String dateOfMatch) {
        this.dateOfMatch = dateOfMatch;
    }

    public String getIsPostponed() {
        return this.isPostponed;
    }

    public void setIsPostponed(String isPostponed) {
        this.isPostponed = isPostponed;
    }

    public Team getTeamHome() {
        return this.teamHome;
    }

    public void setTeamHome(Team teamHome) {
        this.teamHome = teamHome;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public List<Action> getActions() {
        return this.actions;
    }

    public void setActions(List<Action> actions) {
        this.actions = actions;
    }
}
